language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - wget -O phive.phar https://phar.io/releases/phive.phar
  - wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
  - gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - chmod +x phive.phar
  - ./phive.phar install

script:
  - ./tools/phpunit
